/**
 * Image standardization + watermark pipeline for Dezire Sports Wear
 *
 * What it does:
 *  1. Copies raw WhatsApp photos to public/Jerseys/_originals/ (untouched)
 *  2. Standardizes each image:
 *       - Resize + pad to 600×800 (3:4 portrait) on a white background
 *       - Auto-normalize brightness/contrast (equalizes histogram)
 *       - Sharpen slightly for web clarity
 *  3. Bakes a diagonal tiled "DEZIRE SPORTS WEAR" watermark via SVG composite
 *  4. Outputs design-001.jpg … design-100.jpg  (full size, 85% quality)
 *  5. Outputs thumb-001.jpg … thumb-100.jpg   (300×400, 80% quality, fast tiles)
 *  6. Writes src/designs.js manifest
 */

import sharp from 'sharp';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'public', 'Jerseys');
const ORIG_DIR = path.join(SRC_DIR, '_originals');
const OUT_DIR = SRC_DIR;

const FULL_W = 600, FULL_H = 800;
const THUMB_W = 300, THUMB_H = 400;

// ----- build watermark SVG tile -----
function makeWatermarkSvg(w, h) {
  // 24 repetitions across the image in diagonal
  const rows = [];
  const step = 90;
  for (let y = -h; y < h * 2; y += step) {
    for (let x = -w; x < w * 2; x += step * 2) {
      rows.push(`<text x="${x}" y="${y}" transform="rotate(-35,${x},${y})"
        font-family="Arial,Helvetica,sans-serif" font-size="14" font-weight="700"
        letter-spacing="2" fill="white" opacity="0.30">DEZIRE SPORTS WEAR</text>`);
    }
  }
  return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}">
    <rect width="${w}" height="${h}" fill="none"/>
    ${rows.join('\n')}
  </svg>`);
}

// ----- helpers -----
function padNum(n) { return String(n).padStart(3, '0'); }

async function processImage(srcPath, destFull, destThumb, wmW, wmH) {
  const base = sharp(srcPath).rotate(); // auto-orient via EXIF

  // Standardize: contain inside canvas with white background
  const normalized = base
    .resize(wmW, wmH, { fit: 'contain', background: { r: 255, g: 255, b: 255, alpha: 1 } })
    .normalise()             // auto brightness/contrast
    .sharpen({ sigma: 0.8 }); // subtle sharpening

  const buf = await normalized.toBuffer();

  const wmSvg = makeWatermarkSvg(wmW, wmH);

  // Full size with watermark
  await sharp(buf)
    .composite([{ input: wmSvg, blend: 'over' }])
    .jpeg({ quality: 85, mozjpeg: true })
    .toFile(destFull);

  // Thumbnail with watermark
  const wmSvgThumb = makeWatermarkSvg(THUMB_W, THUMB_H);
  await sharp(buf)
    .resize(THUMB_W, THUMB_H, { fit: 'fill' })
    .composite([{ input: wmSvgThumb, blend: 'over' }])
    .jpeg({ quality: 80, mozjpeg: true })
    .toFile(destThumb);
}

// ----- main -----
async function main() {
  // Gather source jpegs (exclude _originals dir and already-processed files)
  const allFiles = fs.readdirSync(SRC_DIR)
    .filter(f => /\.(jpg|jpeg)$/i.test(f) && !f.startsWith('design-') && !f.startsWith('thumb-'))
    .sort();

  console.log(`Found ${allFiles.length} source images.`);
  if (allFiles.length === 0) {
    console.log('Nothing to process. Exiting.');
    return;
  }

  const manifest = [];

  for (let i = 0; i < allFiles.length; i++) {
    const src = path.join(SRC_DIR, allFiles[i]);
    const id = padNum(i + 1);
    const origDest = path.join(ORIG_DIR, `design-${id}.jpg`);
    const fullDest = path.join(OUT_DIR, `design-${id}.jpg`);
    const thumbDest = path.join(OUT_DIR, `thumb-${id}.jpg`);

    // Copy original untouched
    if (!fs.existsSync(origDest)) fs.copyFileSync(src, origDest);

    process.stdout.write(`\r  Processing ${id}/${padNum(allFiles.length)}…`);
    await processImage(src, fullDest, thumbDest, FULL_W, FULL_H);

    manifest.push({ id, full: `/Jerseys/design-${id}.jpg`, thumb: `/Jerseys/thumb-${id}.jpg` });
  }

  console.log('\n  Done processing images.');

  // Write manifest
  const manifestPath = path.join(ROOT, 'src', 'designs.js');
  const content = `// Auto-generated by scripts/watermark.mjs — do not edit manually\nexport const designs = ${JSON.stringify(manifest, null, 2)};\n`;
  fs.writeFileSync(manifestPath, content, 'utf8');
  console.log(`  Manifest written: src/designs.js (${manifest.length} entries)`);
}

main().catch(err => { console.error(err); process.exit(1); });
