// Auto-generated by scripts/watermark.mjs — do not edit manually
export const designs = [
  {
    "id": "001",
    "full": "/Jerseys/design-001.jpg",
    "thumb": "/Jerseys/thumb-001.jpg"
  },
  {
    "id": "002",
    "full": "/Jerseys/design-002.jpg",
    "thumb": "/Jerseys/thumb-002.jpg"
  },
  {
    "id": "003",
    "full": "/Jerseys/design-003.jpg",
    "thumb": "/Jerseys/thumb-003.jpg"
  },
  {
    "id": "004",
    "full": "/Jerseys/design-004.jpg",
    "thumb": "/Jerseys/thumb-004.jpg"
  },
  {
    "id": "005",
    "full": "/Jerseys/design-005.jpg",
    "thumb": "/Jerseys/thumb-005.jpg"
  },
  {
    "id": "006",
    "full": "/Jerseys/design-006.jpg",
    "thumb": "/Jerseys/thumb-006.jpg"
  },
  {
    "id": "007",
    "full": "/Jerseys/design-007.jpg",
    "thumb": "/Jerseys/thumb-007.jpg"
  },
  {
    "id": "008",
    "full": "/Jerseys/design-008.jpg",
    "thumb": "/Jerseys/thumb-008.jpg"
  },
  {
    "id": "009",
    "full": "/Jerseys/design-009.jpg",
    "thumb": "/Jerseys/thumb-009.jpg"
  },
  {
    "id": "010",
    "full": "/Jerseys/design-010.jpg",
    "thumb": "/Jerseys/thumb-010.jpg"
  },
  {
    "id": "011",
    "full": "/Jerseys/design-011.jpg",
    "thumb": "/Jerseys/thumb-011.jpg"
  },
  {
    "id": "012",
    "full": "/Jerseys/design-012.jpg",
    "thumb": "/Jerseys/thumb-012.jpg"
  },
  {
    "id": "013",
    "full": "/Jerseys/design-013.jpg",
    "thumb": "/Jerseys/thumb-013.jpg"
  },
  {
    "id": "014",
    "full": "/Jerseys/design-014.jpg",
    "thumb": "/Jerseys/thumb-014.jpg"
  },
  {
    "id": "015",
    "full": "/Jerseys/design-015.jpg",
    "thumb": "/Jerseys/thumb-015.jpg"
  },
  {
    "id": "016",
    "full": "/Jerseys/design-016.jpg",
    "thumb": "/Jerseys/thumb-016.jpg"
  },
  {
    "id": "017",
    "full": "/Jerseys/design-017.jpg",
    "thumb": "/Jerseys/thumb-017.jpg"
  },
  {
    "id": "018",
    "full": "/Jerseys/design-018.jpg",
    "thumb": "/Jerseys/thumb-018.jpg"
  },
  {
    "id": "019",
    "full": "/Jerseys/design-019.jpg",
    "thumb": "/Jerseys/thumb-019.jpg"
  },
  {
    "id": "020",
    "full": "/Jerseys/design-020.jpg",
    "thumb": "/Jerseys/thumb-020.jpg"
  },
  {
    "id": "021",
    "full": "/Jerseys/design-021.jpg",
    "thumb": "/Jerseys/thumb-021.jpg"
  },
  {
    "id": "022",
    "full": "/Jerseys/design-022.jpg",
    "thumb": "/Jerseys/thumb-022.jpg"
  },
  {
    "id": "023",
    "full": "/Jerseys/design-023.jpg",
    "thumb": "/Jerseys/thumb-023.jpg"
  },
  {
    "id": "024",
    "full": "/Jerseys/design-024.jpg",
    "thumb": "/Jerseys/thumb-024.jpg"
  },
  {
    "id": "025",
    "full": "/Jerseys/design-025.jpg",
    "thumb": "/Jerseys/thumb-025.jpg"
  },
  {
    "id": "026",
    "full": "/Jerseys/design-026.jpg",
    "thumb": "/Jerseys/thumb-026.jpg"
  },
  {
    "id": "027",
    "full": "/Jerseys/design-027.jpg",
    "thumb": "/Jerseys/thumb-027.jpg"
  },
  {
    "id": "028",
    "full": "/Jerseys/design-028.jpg",
    "thumb": "/Jerseys/thumb-028.jpg"
  },
  {
    "id": "029",
    "full": "/Jerseys/design-029.jpg",
    "thumb": "/Jerseys/thumb-029.jpg"
  },
  {
    "id": "030",
    "full": "/Jerseys/design-030.jpg",
    "thumb": "/Jerseys/thumb-030.jpg"
  },
  {
    "id": "031",
    "full": "/Jerseys/design-031.jpg",
    "thumb": "/Jerseys/thumb-031.jpg"
  },
  {
    "id": "032",
    "full": "/Jerseys/design-032.jpg",
    "thumb": "/Jerseys/thumb-032.jpg"
  },
  {
    "id": "033",
    "full": "/Jerseys/design-033.jpg",
    "thumb": "/Jerseys/thumb-033.jpg"
  },
  {
    "id": "034",
    "full": "/Jerseys/design-034.jpg",
    "thumb": "/Jerseys/thumb-034.jpg"
  },
  {
    "id": "035",
    "full": "/Jerseys/design-035.jpg",
    "thumb": "/Jerseys/thumb-035.jpg"
  },
  {
    "id": "036",
    "full": "/Jerseys/design-036.jpg",
    "thumb": "/Jerseys/thumb-036.jpg"
  },
  {
    "id": "037",
    "full": "/Jerseys/design-037.jpg",
    "thumb": "/Jerseys/thumb-037.jpg"
  },
  {
    "id": "038",
    "full": "/Jerseys/design-038.jpg",
    "thumb": "/Jerseys/thumb-038.jpg"
  },
  {
    "id": "039",
    "full": "/Jerseys/design-039.jpg",
    "thumb": "/Jerseys/thumb-039.jpg"
  },
  {
    "id": "040",
    "full": "/Jerseys/design-040.jpg",
    "thumb": "/Jerseys/thumb-040.jpg"
  },
  {
    "id": "041",
    "full": "/Jerseys/design-041.jpg",
    "thumb": "/Jerseys/thumb-041.jpg"
  },
  {
    "id": "042",
    "full": "/Jerseys/design-042.jpg",
    "thumb": "/Jerseys/thumb-042.jpg"
  },
  {
    "id": "043",
    "full": "/Jerseys/design-043.jpg",
    "thumb": "/Jerseys/thumb-043.jpg"
  },
  {
    "id": "044",
    "full": "/Jerseys/design-044.jpg",
    "thumb": "/Jerseys/thumb-044.jpg"
  },
  {
    "id": "045",
    "full": "/Jerseys/design-045.jpg",
    "thumb": "/Jerseys/thumb-045.jpg"
  },
  {
    "id": "046",
    "full": "/Jerseys/design-046.jpg",
    "thumb": "/Jerseys/thumb-046.jpg"
  },
  {
    "id": "047",
    "full": "/Jerseys/design-047.jpg",
    "thumb": "/Jerseys/thumb-047.jpg"
  },
  {
    "id": "048",
    "full": "/Jerseys/design-048.jpg",
    "thumb": "/Jerseys/thumb-048.jpg"
  },
  {
    "id": "049",
    "full": "/Jerseys/design-049.jpg",
    "thumb": "/Jerseys/thumb-049.jpg"
  },
  {
    "id": "050",
    "full": "/Jerseys/design-050.jpg",
    "thumb": "/Jerseys/thumb-050.jpg"
  },
  {
    "id": "051",
    "full": "/Jerseys/design-051.jpg",
    "thumb": "/Jerseys/thumb-051.jpg"
  },
  {
    "id": "052",
    "full": "/Jerseys/design-052.jpg",
    "thumb": "/Jerseys/thumb-052.jpg"
  },
  {
    "id": "053",
    "full": "/Jerseys/design-053.jpg",
    "thumb": "/Jerseys/thumb-053.jpg"
  },
  {
    "id": "054",
    "full": "/Jerseys/design-054.jpg",
    "thumb": "/Jerseys/thumb-054.jpg"
  },
  {
    "id": "055",
    "full": "/Jerseys/design-055.jpg",
    "thumb": "/Jerseys/thumb-055.jpg"
  },
  {
    "id": "056",
    "full": "/Jerseys/design-056.jpg",
    "thumb": "/Jerseys/thumb-056.jpg"
  },
  {
    "id": "057",
    "full": "/Jerseys/design-057.jpg",
    "thumb": "/Jerseys/thumb-057.jpg"
  },
  {
    "id": "058",
    "full": "/Jerseys/design-058.jpg",
    "thumb": "/Jerseys/thumb-058.jpg"
  },
  {
    "id": "059",
    "full": "/Jerseys/design-059.jpg",
    "thumb": "/Jerseys/thumb-059.jpg"
  },
  {
    "id": "060",
    "full": "/Jerseys/design-060.jpg",
    "thumb": "/Jerseys/thumb-060.jpg"
  },
  {
    "id": "061",
    "full": "/Jerseys/design-061.jpg",
    "thumb": "/Jerseys/thumb-061.jpg"
  },
  {
    "id": "062",
    "full": "/Jerseys/design-062.jpg",
    "thumb": "/Jerseys/thumb-062.jpg"
  },
  {
    "id": "063",
    "full": "/Jerseys/design-063.jpg",
    "thumb": "/Jerseys/thumb-063.jpg"
  },
  {
    "id": "064",
    "full": "/Jerseys/design-064.jpg",
    "thumb": "/Jerseys/thumb-064.jpg"
  },
  {
    "id": "065",
    "full": "/Jerseys/design-065.jpg",
    "thumb": "/Jerseys/thumb-065.jpg"
  },
  {
    "id": "066",
    "full": "/Jerseys/design-066.jpg",
    "thumb": "/Jerseys/thumb-066.jpg"
  },
  {
    "id": "067",
    "full": "/Jerseys/design-067.jpg",
    "thumb": "/Jerseys/thumb-067.jpg"
  },
  {
    "id": "068",
    "full": "/Jerseys/design-068.jpg",
    "thumb": "/Jerseys/thumb-068.jpg"
  },
  {
    "id": "069",
    "full": "/Jerseys/design-069.jpg",
    "thumb": "/Jerseys/thumb-069.jpg"
  },
  {
    "id": "070",
    "full": "/Jerseys/design-070.jpg",
    "thumb": "/Jerseys/thumb-070.jpg"
  },
  {
    "id": "071",
    "full": "/Jerseys/design-071.jpg",
    "thumb": "/Jerseys/thumb-071.jpg"
  },
  {
    "id": "072",
    "full": "/Jerseys/design-072.jpg",
    "thumb": "/Jerseys/thumb-072.jpg"
  },
  {
    "id": "073",
    "full": "/Jerseys/design-073.jpg",
    "thumb": "/Jerseys/thumb-073.jpg"
  },
  {
    "id": "074",
    "full": "/Jerseys/design-074.jpg",
    "thumb": "/Jerseys/thumb-074.jpg"
  },
  {
    "id": "075",
    "full": "/Jerseys/design-075.jpg",
    "thumb": "/Jerseys/thumb-075.jpg"
  },
  {
    "id": "076",
    "full": "/Jerseys/design-076.jpg",
    "thumb": "/Jerseys/thumb-076.jpg"
  },
  {
    "id": "077",
    "full": "/Jerseys/design-077.jpg",
    "thumb": "/Jerseys/thumb-077.jpg"
  },
  {
    "id": "078",
    "full": "/Jerseys/design-078.jpg",
    "thumb": "/Jerseys/thumb-078.jpg"
  },
  {
    "id": "079",
    "full": "/Jerseys/design-079.jpg",
    "thumb": "/Jerseys/thumb-079.jpg"
  },
  {
    "id": "080",
    "full": "/Jerseys/design-080.jpg",
    "thumb": "/Jerseys/thumb-080.jpg"
  },
  {
    "id": "081",
    "full": "/Jerseys/design-081.jpg",
    "thumb": "/Jerseys/thumb-081.jpg"
  },
  {
    "id": "082",
    "full": "/Jerseys/design-082.jpg",
    "thumb": "/Jerseys/thumb-082.jpg"
  },
  {
    "id": "083",
    "full": "/Jerseys/design-083.jpg",
    "thumb": "/Jerseys/thumb-083.jpg"
  },
  {
    "id": "084",
    "full": "/Jerseys/design-084.jpg",
    "thumb": "/Jerseys/thumb-084.jpg"
  },
  {
    "id": "085",
    "full": "/Jerseys/design-085.jpg",
    "thumb": "/Jerseys/thumb-085.jpg"
  },
  {
    "id": "086",
    "full": "/Jerseys/design-086.jpg",
    "thumb": "/Jerseys/thumb-086.jpg"
  },
  {
    "id": "087",
    "full": "/Jerseys/design-087.jpg",
    "thumb": "/Jerseys/thumb-087.jpg"
  },
  {
    "id": "088",
    "full": "/Jerseys/design-088.jpg",
    "thumb": "/Jerseys/thumb-088.jpg"
  },
  {
    "id": "089",
    "full": "/Jerseys/design-089.jpg",
    "thumb": "/Jerseys/thumb-089.jpg"
  },
  {
    "id": "090",
    "full": "/Jerseys/design-090.jpg",
    "thumb": "/Jerseys/thumb-090.jpg"
  },
  {
    "id": "091",
    "full": "/Jerseys/design-091.jpg",
    "thumb": "/Jerseys/thumb-091.jpg"
  },
  {
    "id": "092",
    "full": "/Jerseys/design-092.jpg",
    "thumb": "/Jerseys/thumb-092.jpg"
  },
  {
    "id": "093",
    "full": "/Jerseys/design-093.jpg",
    "thumb": "/Jerseys/thumb-093.jpg"
  },
  {
    "id": "094",
    "full": "/Jerseys/design-094.jpg",
    "thumb": "/Jerseys/thumb-094.jpg"
  },
  {
    "id": "095",
    "full": "/Jerseys/design-095.jpg",
    "thumb": "/Jerseys/thumb-095.jpg"
  },
  {
    "id": "096",
    "full": "/Jerseys/design-096.jpg",
    "thumb": "/Jerseys/thumb-096.jpg"
  },
  {
    "id": "097",
    "full": "/Jerseys/design-097.jpg",
    "thumb": "/Jerseys/thumb-097.jpg"
  },
  {
    "id": "098",
    "full": "/Jerseys/design-098.jpg",
    "thumb": "/Jerseys/thumb-098.jpg"
  },
  {
    "id": "099",
    "full": "/Jerseys/design-099.jpg",
    "thumb": "/Jerseys/thumb-099.jpg"
  },
  {
    "id": "100",
    "full": "/Jerseys/design-100.jpg",
    "thumb": "/Jerseys/thumb-100.jpg"
  }
];
